# portal/check_login_page.py
"""
Quick health‑check: verify that the CAPTCHA selector still matches an image.
If it does *not* match, a Windows toast (and optional Discord webhook) is sent.
"""

import json, os, subprocess, sys

# Ensure UTF‑8 console output on Windows
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

# Add repository root to PYTHONPATH so we can import portal modules
repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

from portal.webcmd_adapter import WebCMDAdapter, _load_env_file
from portal.notifier import send_toast

# Load .env (username/password not needed for this check but we need KP_BASE_URL)
_load_env_file()

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "config.json")
DEFAULT_SELECTOR = "img[src*='Captcha']"

def load_selector() -> str:
    if os.path.exists(CONFIG_PATH):
        try:
            with open(CONFIG_PATH, "r", encoding="utf-8") as f:
                cfg = json.load(f)
                return cfg.get("captcha_selector", DEFAULT_SELECTOR)
        except Exception as e:
            print(f"[⚠️] Failed to read config.json ({e}); using default selector.")
    return DEFAULT_SELECTOR

CAPTCHA_SELECTOR = load_selector()

base_url = os.getenv("KP_BASE_URL", "https://kp.christuniversity.in/KnowledgePro")

adapter = WebCMDAdapter()
bin_path = adapter._get_webcmd_bin()
session_id = adapter._ensure_session()

# -----------------------------------------------------------------
# Tiny WebCMD script – just load the page and report if selector exists
# -----------------------------------------------------------------
js = f"""
await page.goto('{base_url}/StudentLogin.do', {{waitUntil:'networkidle'}});
const el = await page.$('{CAPTCHA_SELECTOR}');
console.log(JSON.stringify({{found: !!el}}));
"""

tmp_js_path = os.path.join(os.path.dirname(__file__), "adapters", "_temp_check.js")
with open(tmp_js_path, "w", encoding="utf-8") as f:
    f.write(js)

cmd = [bin_path, "--profile", adapter.profile]
if session_id:
    cmd.extend(["--session", session_id])
cmd.extend(["browser", "run", "--file", tmp_js_path])

result = subprocess.run(cmd, capture_output=True, text=True, timeout=30, shell=(sys.platform == "win32"))
found = False
for line in (result.stdout + "\n" + result.stderr).splitlines():
    if '"found":' in line:
        try:
            payload = json.loads(line)
            found = payload.get('found', False)
        except Exception:
            pass
        break

if not found:
    send_toast(
        title="⚠️ CAPTCHA selector broken",
        message=(
            f"The selector {CAPTCHA_SELECTOR!r} no longer matches an image on the login page. "
            "Open login_page_dump.html (generated by the scraper) and update portal/config.json."
        ),
    )
    sys.exit(1)
else:
    print("[✅] CAPTCHA selector is working.")
    sys.exit(0)
